version: '3.8'

services:
  employeeservice_db:
    image: mysql:8
    container_name: employeeservice_db
    environment:
      MYSQL_ROOT_PASSWORD: 'pxl'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: employeeservice_db
    ports:
    - "3306:3306"
    restart: always

  # Service voor de Department database
  departmentservice_db:
    image: mysql:8
    container_name: departmentservice_db
    environment:
      MYSQL_ROOT_PASSWORD: 'pxl'
      MYSQL_DATABASE: departmentservice_db # Andere databasenaam
    ports:
      # Host poort 3307 wordt gekoppeld aan container poort 3306
      - "3307:3306"
    restart: always

    # Service voor de Organization database
  organizationservice_db:
    image: mysql:8
    container_name: organizationservice_db
    environment:
      MYSQL_ROOT_PASSWORD: 'pxl'
      MYSQL_DATABASE: organizationservice_db # Andere databasenaam
    ports:
      # Host poort 3308 wordt gekoppeld aan container poort 3306
      - "3308:3306"
    restart: always
